baseURL = "https://exifcleaner.com/"
languageCode = "en-us"
title = "ExifCleaner"
theme = "vex-hugo"
assetDir = "assets"

#################################### Plugins ##########################################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://fonts.googleapis.com/css?family=Droid+Serif:400i|Source+Sans+Pro:300,400,600,700"
  [[params.plugins.css]]
  URL = "https://fonts.googleapis.com/css?family=Josefin+Sans:300,400,600,700"
  [[params.plugins.css]]
  URL = "css/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "css/themefisher-fonts.css"
  [[params.plugins.css]]
  URL = "css/owl.carousel.css"
  [[params.plugins.css]]
  URL = "css/magnific-popup.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/jquery-2.1.1.min.js"
  [[params.plugins.js]]
  URL = "js/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "js/owl.carousel.min.js"
  [[params.plugins.js]]
  URL = "js/jquery.magnific-popup.min.js"


###### node_modules JS assets #######
[module]

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "node_modules"
    target = "assets"


###################################### Navigation ######################################
[menu]
    
  [[menu.main]]
  name = "Download"
  URL = "https://github.com/szTheory/exifcleaner/releases"
  weight = 2
  
  [[menu.main]]
  name = "Source Code"
  URL = "https://github.com/szTheory/exifcleaner"
  weight = 3

########################### Default parameters ##########################
[params]
logo = ""
home = "Home"
# Meta data
description = "Desktop app to clean image metadata"
author = "szTheory"
# copyright
copyright = "Copyright 2019 &copy; [szTheory](http://github.com/szTheory) | All right reserved."
pageTitle = "ExifCleaner - Desktop app to clean image metadata"

  # Preloader
  [params.preloader]
  enable = false