baseURL = "https://exifcleaner.com/"
languageCode = "en-us"
title = "ExifCleaner"
theme = "vex-hugo"

###### node_modules JS assets #######
[module]

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "node_modules"
    target = "assets"


###################################### Navigation ######################################
[menu]
    
  [[menu.main]]
  name = "Download"
  URL = "https://github.com/szTheory/exifcleaner/releases"
  weight = 2
  
  [[menu.main]]
  name = "Source Code"
  URL = "https://github.com/szTheory/exifcleaner"
  weight = 3

########################### Default parameters ##########################
[params]
logo = ""
home = "Home"
# Meta data
description = "Desktop app to clean image metadata"
author = "szTheory"
# copyright
copyright = "Copyright 2019 &copy; [szTheory](http://github.com/szTheory) | All right reserved."
pageTitle = "ExifCleaner - Desktop app to clean image metadata"

  # Preloader
  [params.preloader]
  enable = false